const types = {
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_SIDEBAR_SHOW: 'TOGGLE_SIDEBAR_SHOW',
  TOGGLE_DEVICE: "TOGGLE_DEVICE",
  EXPAND_MENU: 'EXPAND_MENU',
  SWITCH_EFFECT: 'SWITCH_EFFECT',
  LOAD_MENU: 'LOAD_MENU',
  LOAD_ADMINS: 'LOAD_ADMINS',
  LOAD_ADMINDEPARTMENT: 'LOAD_ADMINDEPARTMENT',
  LOAD_ADMINDEPARTMENT_TREE:'LOAD_ADMINDEPARTMENT_TREE',
  LOAD_ADMINROLES: 'LOAD_ADMINROLES',
  SYS_ADMINS_GET: 'SYS_ADMINS_GET',
  LOAD_CURRENT_MENU: 'LOAD_CURRENT_MENU',
  SET_USER_INFO: 'SET_USER_INFO',
  LOAD_PERMISSIONSTREE: 'LOAD_PERMISSIONSTREE',
  FRONTEND_PERMISSION_ALLS: 'FRONTEND_PERMISSION_ALLS'
}

export default types
